spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/todo?characterEncoding=utf-8&useSSL=false
    username: root
    password: 214057
  redis:
    host: localhost
    port: 8001
  server:
    port: 8001
      servlet:
        context-path: /TODO
mybatis:
 mapper-locations:  classpath:mapper/*.xml
 type-aliases-package:  com.todo.demo.entity
 configuration:
  map-underscore-to-camel-case:  true # 开启驼峰命名
  log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl # 日志