server.port=8001

spring.datasource.url=jdbc:mysql://localhost:3306/todo?serverTimezone=GMT%2b8 &characterEncoding=utf-8&useSSL=false&debug:true
spring.datasource.username=root
spring.datasource.password=214057
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver